// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP8ZlqxxYNUWFqOUFmvc6stI9aVc4Ilmw',
    appId: '1:606308113263:ios:8370dffe3d2f53ed7a269a',
    messagingSenderId: '606308113263',
    projectId: 'samdechovmae-rtk',
    storageBucket: 'samdechovmae-rtk.appspot.com',
    iosBundleId: 'com.thearamot.sommobile.somMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDcFFsCMdFHP6sWOXy_NVS8Z0hJbguLI',
    appId: '1:606308113263:web:ac1914ddcc8b26d57a269a',
    messagingSenderId: '606308113263',
    projectId: 'samdechovmae-rtk',
    authDomain: 'samdechovmae-rtk.firebaseapp.com',
    storageBucket: 'samdechovmae-rtk.appspot.com',
    measurementId: 'G-VB3KDL5Y6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPjuTpAMtVgZHMMCB3cTunNJ_AJF1Az0',
    appId: '1:606308113263:android:083a2cb9c3f3f3e37a269a',
    messagingSenderId: '606308113263',
    projectId: 'samdechovmae-rtk',
    storageBucket: 'samdechovmae-rtk.appspot.com',
  );

}